

DELETE FROM department_roles;
DELETE FROM departments;
ALTER TABLE department_roles DROP CONSTRAINT department_roles_ln_department_role_id_fkey;



INSERT INTO departments (department_id, ln_department_id, org_id, department_name, active, petty_cash, description, duties, reports, details) VALUES (0, 0, 0, 'Board of Directors', true, false, NULL, NULL, NULL, NULL);
INSERT INTO departments (department_id, ln_department_id, org_id, department_name, active, petty_cash, description, duties, reports, details) VALUES (1, 0, 0, 'Research', true, false, NULL, NULL, NULL, NULL);
INSERT INTO departments (department_id, ln_department_id, org_id, department_name, active, petty_cash, description, duties, reports, details) VALUES (2, 0, 0, 'Research Capacity Strengthening Division', true, false, NULL, NULL, NULL, NULL);
INSERT INTO departments (department_id, ln_department_id, org_id, department_name, active, petty_cash, description, duties, reports, details) VALUES (3, 0, 0, 'Policy Engagement and Communications', true, false, NULL, NULL, NULL, NULL);
INSERT INTO departments (department_id, ln_department_id, org_id, department_name, active, petty_cash, description, duties, reports, details) VALUES (4, 4, 0, 'Operations', true, false, NULL, NULL, NULL, NULL);



INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (47, 4, 69, 0, 'Field Interviewer', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (53, 4, 69, 0, 'Editor', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (48, 4, 69, 0, 'Field Team Leader', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (62, 4, 69, 0, 'HEAD OF FINANCE AND ADMINISTRATION', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (32, 3, 1, 0, 'Head of Policy Engagement and Communication', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (18, 4, 20, 0, 'IT Support Assistant', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (30, 2, 66, 0, 'Intern', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (57, 2, 66, 0, 'Visiting scholar', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (55, 4, 1, 0, 'Packard Field coordinator', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (33, 3, 32, 0, 'Policy Engagement Manager', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (67, 4, 69, 0, 'Risk and Compliance Manager', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (59, 0, 1, 0, 'Senior Advisor to Executive Director', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (65, 4, 69, 0, 'Program Coordinator', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (49, 4, 20, 0, 'Site Supervisor', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (50, 1, 66, 0, 'Transcriber', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (51, 1, 66, 0, 'Translator', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (12, 1, 66, 0, 'Office Assistant', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (6, 4, 69, 0, 'Accounts Assistant', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (17, 4, 69, 0, 'Systems Administrator', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (27, 1, 66, 0, 'Research Officer', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (68, 1, 66, 0, 'Research Fellow', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (7, 4, 69, 0, 'Human Resources Manager', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (2, 4, 69, 0, 'Head of Finance & Administration', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (3, 4, 69, 0, 'Finance Manager', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (1, 0, 1, 0, 'Executive Director', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (24, 1, 66, 0, 'Associate Research Scientist', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (23, 1, 66, 0, 'Research Scientist', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (29, 1, 66, 0, 'Research Trainee', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (26, 1, 66, 0, 'Senior Research Officer', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (22, 1, 66, 0, 'Senior Research Scientist', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (66, 1, 1, 0, 'Director of Research', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (69, 4, 1, 0, 'Director of Operations', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (64, 4, 69, 0, 'Admin. Assistant', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (52, 4, 20, 0, 'Coder', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (54, 4, 20, 0, 'Assistant Database Programmer', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (38, 2, 37, 0, 'CARTA Communications Officer', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (37, 2, 1, 0, 'CARTA Program Manager', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (36, 3, 32, 0, 'Communications Assistant', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (35, 3, 32, 0, 'Communications Officer', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (8, 4, 69, 0, 'Human Resources Officer', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (15, 4, 69, 0, 'Program Assistant', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (5, 4, 69, 0, 'Financial Accountant', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (4, 4, 69, 0, 'Project Accountant', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (11, 4, 69, 0, 'Receptionist/Administrative Assistant', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (56, 4, 69, 0, 'Development Manager', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (9, 4, 69, 0, 'Senior Human Resources Assistant', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (61, 4, 69, 0, 'FACILITY MANAGER', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (20, 4, 69, 0, 'IT Manager', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (16, 4, 69, 0, 'Executive Assistant', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (58, 4, 69, 0, 'M & E Officer', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (63, 4, 69, 0, 'M & E COUNTRY MANAGER - KENYA', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (42, 4, 69, 0, 'M&E Country Manager - Kenya', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (44, 4, 69, 0, 'M&E Country Manager - Nigeria', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (41, 4, 69, 0, 'M&E Technical Lead', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (43, 4, 69, 0, 'M&E Country Manager - Senegal', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (60, 4, 69, 0, 'M&E Officer', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (34, 3, 32, 0, 'Webmaster', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (25, 2, 66, 0, 'Post-Doctoral Fellow', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (21, 1, 66, 0, 'Database Programmer', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (40, 1, 66, 0, 'DSS Field Coordinator', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (28, 1, 66, 0, 'Research Assistant', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (31, 1, 66, 0, 'Data Analyst', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (70, 1, 66, 0, 'Senior Assistant Database Programmer', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (39, 1, 66, 0, 'Community Relations Officer', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (19, 1, 66, 0, 'Data Systems Manager', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (46, 1, 66, 0, 'Data Entry Supervisor', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (10, 4, 69, 0, 'Senior Administrative Assistant', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (45, 1, 66, 0, 'Data Entry Clerk', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (13, 4, 69, 0, 'Driver/Office Assistant', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (71, 1, 66, 0, 'DSS Site Supervisor', true, NULL, NULL, NULL, NULL, NULL);
INSERT INTO department_roles (department_role_id, department_id, ln_department_role_id, org_id, department_role_name, active, job_description, job_requirements, duties, performance_measures, details) VALUES (14, 4, 69, 0, 'Executive Driver', true, NULL, NULL, NULL, NULL, NULL);



SELECT pg_catalog.setval('departments_department_id_seq', 4, true);
SELECT pg_catalog.setval('department_roles_department_role_id_seq', 9, true);


ALTER TABLE department_roles
  ADD CONSTRAINT department_roles_ln_department_role_id_fkey FOREIGN KEY (ln_department_role_id)
      REFERENCES department_roles (department_role_id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION;



