INSERT INTO sys_continents (sys_continent_id, sys_continent_name) VALUES ('AF', 'Africa');
INSERT INTO sys_continents (sys_continent_id, sys_continent_name) VALUES ('AS', 'Asia');
INSERT INTO sys_continents (sys_continent_id, sys_continent_name) VALUES ('EU', 'Europe');
INSERT INTO sys_continents (sys_continent_id, sys_continent_name) VALUES ('NA', 'North America');
INSERT INTO sys_continents (sys_continent_id, sys_continent_name) VALUES ('SA', 'South America');
INSERT INTO sys_continents (sys_continent_id, sys_continent_name) VALUES ('OC', 'Oceania');
INSERT INTO sys_continents (sys_continent_id, sys_continent_name) VALUES ('AN', 'Antarctica');

INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'AF', 'AFG', '004', 'Afghanistan');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'AX', 'ALA', '248', 'Aland Islands');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'AL', 'ALB', '008', 'Albania');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'DZ', 'DZA', '012', 'Algeria');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('OC', 'AS', 'ASM', '016', 'American Samoa');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'AD', 'AND', '020', 'Andorra');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'AO', 'AGO', '024', 'Angola');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('NA', 'AI', 'AIA', '660', 'Anguilla');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AN', 'AQ', 'ATA', '010', 'Antarctica');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('NA', 'AG', 'ATG', '028', 'Antigua and Barbuda');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('SA', 'AR', 'ARG', '032', 'Argentina');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'AM', 'ARM', '051', 'Armenia');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('NA', 'AW', 'ABW', '533', 'Aruba');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('OC', 'AU', 'AUS', '036', 'Australia');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'AT', 'AUT', '040', 'Austria');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'AZ', 'AZE', '031', 'Azerbaijan');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('NA', 'BS', 'BHS', '044', 'Bahamas');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'BH', 'BHR', '048', 'Bahrain');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'BD', 'BGD', '050', 'Bangladesh');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('NA', 'BB', 'BRB', '052', 'Barbados');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'BY', 'BLR', '112', 'Belarus');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'BE', 'BEL', '056', 'Belgium');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('NA', 'BZ', 'BLZ', '084', 'Belize');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'BJ', 'BEN', '204', 'Benin');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('NA', 'BM', 'BMU', '060', 'Bermuda');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'BT', 'BTN', '064', 'Bhutan');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('SA', 'BO', 'BOL', '068', 'Bolivia');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'BA', 'BIH', '070', 'Bosnia and Herzegovina');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'BW', 'BWA', '072', 'Botswana');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AN', 'BV', 'BVT', '074', 'Bouvet Island');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('SA', 'BR', 'BRA', '076', 'Brazil');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'IO', 'IOT', '086', 'British Indian Ocean Territory');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('NA', 'VG', 'VGB', '092', 'British Virgin Islands');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'BN', 'BRN', '096', 'Brunei Darussalam');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'BG', 'BGR', '100', 'Bulgaria');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'BF', 'BFA', '854', 'Burkina Faso');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'BI', 'BDI', '108', 'Burundi');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'KH', 'KHM', '116', 'Cambodia');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'CM', 'CMR', '120', 'Cameroon');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('NA', 'CA', 'CAN', '124', 'Canada');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'CV', 'CPV', '132', 'Cape Verde');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('NA', 'KY', 'CYM', '136', 'Cayman Islands');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'CF', 'CAF', '140', 'Central African Republic');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'TD', 'TCD', '148', 'Chad');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('SA', 'CL', 'CHL', '152', 'Chile');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'CN', 'CHN', '156', 'China');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'CX', 'CXR', '162', 'Christmas Island');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'CC', 'CCK', '166', 'Cocos Keeling Islands');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('SA', 'CO', 'COL', '170', 'Colombia');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'KM', 'COM', '174', 'Comoros');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'CD', 'COD', '180', 'Democratic Republic of Congo');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'CG', 'COG', '178', 'Republic of Congo');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('OC', 'CK', 'COK', '184', 'Cook Islands');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('NA', 'CR', 'CRI', '188', 'Costa Rica');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'CI', 'CIV', '384', 'Cote d Ivoire');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'HR', 'HRV', '191', 'Croatia');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('NA', 'CU', 'CUB', '192', 'Cuba');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'CY', 'CYP', '196', 'Cyprus');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'CZ', 'CZE', '203', 'Czech Republic');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'DK', 'DNK', '208', 'Denmark');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'DJ', 'DJI', '262', 'Djibouti');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('NA', 'DM', 'DMA', '212', 'Dominica');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('NA', 'DO', 'DOM', '214', 'Dominican Republic');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('SA', 'EC', 'ECU', '218', 'Ecuador');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'EG', 'EGY', '818', 'Egypt');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('NA', 'SV', 'SLV', '222', 'El Salvador');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'GQ', 'GNQ', '226', 'Equatorial Guinea');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'ER', 'ERI', '232', 'Eritrea');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'EE', 'EST', '233', 'Estonia');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'ET', 'ETH', '231', 'Ethiopia');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'FO', 'FRO', '234', 'Faroe Islands');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('SA', 'FK', 'FLK', '238', 'Falkland Islands');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('OC', 'FJ', 'FJI', '242', 'Fiji');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'FI', 'FIN', '246', 'Finland');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'FR', 'FRA', '250', 'France');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('SA', 'GF', 'GUF', '254', 'French Guiana');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('OC', 'PF', 'PYF', '258', 'French Polynesia');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AN', 'TF', 'ATF', '260', 'French Southern Territories');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'GA', 'GAB', '266', 'Gabon');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'GM', 'GMB', '270', 'Gambia');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'GE', 'GEO', '268', 'Georgia');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'DE', 'DEU', '276', 'Germany');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'GH', 'GHA', '288', 'Ghana');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'GI', 'GIB', '292', 'Gibraltar');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'GR', 'GRC', '300', 'Greece');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('NA', 'GL', 'GRL', '304', 'Greenland');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('NA', 'GD', 'GRD', '308', 'Grenada');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('NA', 'GP', 'GLP', '312', 'Guadeloupe');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('OC', 'GU', 'GUM', '316', 'Guam');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('NA', 'GT', 'GTM', '320', 'Guatemala');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'GG', 'GGY', '831', 'Guernsey');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'GN', 'GIN', '324', 'Guinea');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'GW', 'GNB', '624', 'Guinea-Bissau');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('SA', 'GY', 'GUY', '328', 'Guyana');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('NA', 'HT', 'HTI', '332', 'Haiti');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AN', 'HM', 'HMD', '334', 'Heard Island and McDonald Islands');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'VA', 'VAT', '336', 'Vatican City State');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('NA', 'HN', 'HND', '340', 'Honduras');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'HK', 'HKG', '344', 'Hong Kong');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'HU', 'HUN', '348', 'Hungary');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'IS', 'ISL', '352', 'Iceland');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'IN', 'IND', '356', 'India');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'ID', 'IDN', '360', 'Indonesia');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'IR', 'IRN', '364', 'Iran');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'IQ', 'IRQ', '368', 'Iraq');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'IE', 'IRL', '372', 'Ireland');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'IM', 'IMN', '833', 'Isle of Man');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'IL', 'ISR', '376', 'Israel');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'IT', 'ITA', '380', 'Italy');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('NA', 'JM', 'JAM', '388', 'Jamaica');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'JP', 'JPN', '392', 'Japan');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'JE', 'JEY', '832', 'Bailiwick of Jersey');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'JO', 'JOR', '400', 'Jordan');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'KZ', 'KAZ', '398', 'Kazakhstan');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'KE', 'KEN', '404', 'Kenya');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('OC', 'KI', 'KIR', '296', 'Kiribati');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'KP', 'PRK', '408', 'North Korea');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'KR', 'KOR', '410', 'South Korea');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'KW', 'KWT', '414', 'Kuwait');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'KG', 'KGZ', '417', 'Kyrgyz Republic');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'LA', 'LAO', '418', 'Lao Peoples Democratic Republic');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'LV', 'LVA', '428', 'Latvia');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'LB', 'LBN', '422', 'Lebanon');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'LS', 'LSO', '426', 'Lesotho');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'LR', 'LBR', '430', 'Liberia');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'LY', 'LBY', '434', 'Libyan Arab Jamahiriya');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'LI', 'LIE', '438', 'Liechtenstein');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'LT', 'LTU', '440', 'Lithuania');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'LU', 'LUX', '442', 'Luxembourg');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'MO', 'MAC', '446', 'Macao');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'MK', 'MKD', '807', 'Macedonia');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'MG', 'MDG', '450', 'Madagascar');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'MW', 'MWI', '454', 'Malawi');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'MY', 'MYS', '458', 'Malaysia');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'MV', 'MDV', '462', 'Maldives');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'ML', 'MLI', '466', 'Mali');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'MT', 'MLT', '470', 'Malta');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('OC', 'MH', 'MHL', '584', 'Marshall Islands');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('NA', 'MQ', 'MTQ', '474', 'Martinique');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'MR', 'MRT', '478', 'Mauritania');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'MU', 'MUS', '480', 'Mauritius');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'YT', 'MYT', '175', 'Mayotte');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('NA', 'MX', 'MEX', '484', 'Mexico');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('OC', 'FM', 'FSM', '583', 'Micronesia');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'MD', 'MDA', '498', 'Moldova');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'MC', 'MCO', '492', 'Monaco');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'MN', 'MNG', '496', 'Mongolia');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'ME', 'MNE', '499', 'Montenegro');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('NA', 'MS', 'MSR', '500', 'Montserrat');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'MA', 'MAR', '504', 'Morocco');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'MZ', 'MOZ', '508', 'Mozambique');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'MM', 'MMR', '104', 'Myanmar');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'NA', 'NAM', '516', 'Namibia');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('OC', 'NR', 'NRU', '520', 'Nauru');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'NP', 'NPL', '524', 'Nepal');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('NA', 'AN', 'ANT', '530', 'Netherlands Antilles');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'NL', 'NLD', '528', 'Netherlands');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('OC', 'NC', 'NCL', '540', 'New Caledonia');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('OC', 'NZ', 'NZL', '554', 'New Zealand');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('NA', 'NI', 'NIC', '558', 'Nicaragua');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'NE', 'NER', '562', 'Niger');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'NG', 'NGA', '566', 'Nigeria');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('OC', 'NU', 'NIU', '570', 'Niue');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('OC', 'NF', 'NFK', '574', 'Norfolk Island');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('OC', 'MP', 'MNP', '580', 'Northern Mariana Islands');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'NO', 'NOR', '578', 'Norway');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'OM', 'OMN', '512', 'Oman');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'PK', 'PAK', '586', 'Pakistan');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('OC', 'PW', 'PLW', '585', 'Palau');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'PS', 'PSE', '275', 'Palestinian Territory');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('NA', 'PA', 'PAN', '591', 'Panama');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('OC', 'PG', 'PNG', '598', 'Papua New Guinea');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('SA', 'PY', 'PRY', '600', 'Paraguay');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('SA', 'PE', 'PER', '604', 'Peru');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'PH', 'PHL', '608', 'Philippines');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('OC', 'PN', 'PCN', '612', 'Pitcairn Islands');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'PL', 'POL', '616', 'Poland');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'PT', 'PRT', '620', 'Portugal');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('NA', 'PR', 'PRI', '630', 'Puerto Rico');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'QA', 'QAT', '634', 'Qatar');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'RE', 'REU', '638', 'Reunion');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'RO', 'ROU', '642', 'Romania');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'RU', 'RUS', '643', 'Russian Federation');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'RW', 'RWA', '646', 'Rwanda');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('NA', 'BL', 'BLM', '652', 'Saint Barthelemy');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'SH', 'SHN', '654', 'Saint Helena');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('NA', 'KN', 'KNA', '659', 'Saint Kitts and Nevis');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('NA', 'LC', 'LCA', '662', 'Saint Lucia');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('NA', 'MF', 'MAF', '663', 'Saint Martin');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('NA', 'PM', 'SPM', '666', 'Saint Pierre and Miquelon');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('NA', 'VC', 'VCT', '670', 'Saint Vincent and the Grenadines');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('OC', 'WS', 'WSM', '882', 'Samoa');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'SM', 'SMR', '674', 'San Marino');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'ST', 'STP', '678', 'Sao Tome and Principe');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'SA', 'SAU', '682', 'Saudi Arabia');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'SN', 'SEN', '686', 'Senegal');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'RS', 'SRB', '688', 'Serbia');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'SC', 'SYC', '690', 'Seychelles');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'SL', 'SLE', '694', 'Sierra Leone');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'SG', 'SGP', '702', 'Singapore');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'SK', 'SVK', '703', 'Slovakia');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'SI', 'SVN', '705', 'Slovenia');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('OC', 'SB', 'SLB', '090', 'Solomon Islands');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'SO', 'SOM', '706', 'Somalia');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'ZA', 'ZAF', '710', 'South Africa');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AN', 'GS', 'SGS', '239', 'South Georgia and the South Sandwich Islands');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'ES', 'ESP', '724', 'Spain');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'LK', 'LKA', '144', 'Sri Lanka');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'SD', 'SDN', '736', 'Sudan');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'SS', 'SSN', '737', 'South Sudan');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('SA', 'SR', 'SUR', '740', 'Suriname');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'SJ', 'SJM', '744', 'Svalbard & Jan Mayen Islands');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'SZ', 'SWZ', '748', 'Swaziland');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'SE', 'SWE', '752', 'Sweden');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'CH', 'CHE', '756', 'Switzerland');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'SY', 'SYR', '760', 'Syrian Arab Republic');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'TW', 'TWN', '158', 'Taiwan');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'TJ', 'TJK', '762', 'Tajikistan');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'TZ', 'TZA', '834', 'Tanzania');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'TH', 'THA', '764', 'Thailand');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'TL', 'TLS', '626', 'Timor-Leste');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'TG', 'TGO', '768', 'Togo');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('OC', 'TK', 'TKL', '772', 'Tokelau');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('OC', 'TO', 'TON', '776', 'Tonga');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('NA', 'TT', 'TTO', '780', 'Trinidad and Tobago');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'TN', 'TUN', '788', 'Tunisia');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'TR', 'TUR', '792', 'Turkey');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'TM', 'TKM', '795', 'Turkmenistan');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('NA', 'TC', 'TCA', '796', 'Turks and Caicos Islands');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('OC', 'TV', 'TUV', '798', 'Tuvalu');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'UG', 'UGA', '800', 'Uganda');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'UA', 'UKR', '804', 'Ukraine');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'AE', 'ARE', '784', 'United Arab Emirates');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('EU', 'GB', 'GBR', '826', 'United Kingdom of Great Britain & Northern Ireland');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('NA', 'US', 'USA', '840', 'United States of America');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('OC', 'UM', 'UMI', '581', 'United States Minor Outlying Islands');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('NA', 'VI', 'VIR', '850', 'United States Virgin Islands');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('SA', 'UY', 'URY', '858', 'Uruguay');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'UZ', 'UZB', '860', 'Uzbekistan');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('OC', 'VU', 'VUT', '548', 'Vanuatu');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('SA', 'VE', 'VEN', '862', 'Venezuela');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'VN', 'VNM', '704', 'Vietnam');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('OC', 'WF', 'WLF', '876', 'Wallis and Futuna');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'EH', 'ESH', '732', 'Western Sahara');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AS', 'YE', 'YEM', '887', 'Yemen');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'ZM', 'ZMB', '894', 'Zambia');
INSERT INTO sys_countrys (sys_continent_id, sys_country_id, sys_country_code, sys_country_number, sys_country_name) VALUES ('AF', 'ZW', 'ZWE', '716', 'Zimbabwe');

