


INSERT INTO orgs (org_id, org_name, currency_id, logo) VALUES (1, 'org 1', 1, 'logo.png');
INSERT INTO orgs (org_id, org_name, currency_id, logo) VALUES (2, 'org 2', 1, 'logo.png');
INSERT INTO orgs (org_id, org_name, currency_id, logo) VALUES (3, 'org 3', 1, 'logo.png');
INSERT INTO orgs (org_id, org_name, currency_id, logo) VALUES (4, 'org 4', 1, 'logo.png');
INSERT INTO orgs (org_id, org_name, currency_id, logo) VALUES (5, 'org 5', 1, 'logo.png');
INSERT INTO orgs (org_id, org_name, currency_id, logo) VALUES (6, 'org 6', 1, 'logo.png');
INSERT INTO orgs (org_id, org_name, currency_id, logo) VALUES (7, 'org 7', 1, 'logo.png');
INSERT INTO orgs (org_id, org_name, currency_id, logo) VALUES (8, 'org 8', 1, 'logo.png');
INSERT INTO orgs (org_id, org_name, currency_id, logo) VALUES (9, 'org 9', 1, 'logo.png');
INSERT INTO orgs (org_id, org_name, currency_id, logo) VALUES (10, 'org 10', 1, 'logo.png');
INSERT INTO orgs (org_id, org_name, currency_id, logo) VALUES (11, 'org 11', 1, 'logo.png');
INSERT INTO orgs (org_id, org_name, currency_id, logo) VALUES (12, 'org 12', 1, 'logo.png');
INSERT INTO orgs (org_id, org_name, currency_id, logo) VALUES (13, 'org 13', 1, 'logo.png');
INSERT INTO orgs (org_id, org_name, currency_id, logo) VALUES (14, 'org 14', 1, 'logo.png');

UPDATE orgs SET currency_id = 1, pin = 'P51093731T', logo = 'logo.png';

UPDATE account_types SET org_id = 0;
UPDATE accounts SET org_id = 0;
UPDATE accounts_class SET org_id = 0;
UPDATE address SET org_id = 0;
UPDATE adjustments SET org_id = 0;
UPDATE advance_deductions SET org_id = 0;
UPDATE amortisation SET org_id = 0;
UPDATE applicants SET org_id = 0;
UPDATE applications SET org_id = 0;
UPDATE approval_checklists SET org_id = 0;
UPDATE approvals SET org_id = 0;
UPDATE asset_movement SET org_id = 0;
UPDATE asset_types SET org_id = 0;
UPDATE asset_valuations SET org_id = 0;
UPDATE assets SET org_id = 0;
UPDATE attendance SET org_id = 0;
UPDATE bank_accounts SET org_id = 0;
UPDATE bank_branch SET org_id = 0;
UPDATE banks SET org_id = 0;
UPDATE bidders SET org_id = 0;
UPDATE budget_lines SET org_id = 0;
UPDATE budgets SET org_id = 0;
UPDATE case_types SET org_id = 0;
UPDATE casual_application SET org_id = 0;
UPDATE casual_category SET org_id = 0;
UPDATE casuals SET org_id = 0;
UPDATE checklists SET org_id = 0;
UPDATE contracts SET org_id = 0;
UPDATE currency_rates SET org_id = 0;
UPDATE cv_projects SET org_id = 0;
UPDATE cv_referees SET org_id = 0;
UPDATE cv_seminars SET org_id = 0;
UPDATE default_accounts SET org_id = 0;
UPDATE default_adjustments SET org_id = 0;
UPDATE default_tax_types SET org_id = 0;
UPDATE define_phases SET org_id = 0;
UPDATE define_tasks SET org_id = 0;
UPDATE department_roles SET org_id = 0;
UPDATE departments SET org_id = 0;
UPDATE education SET org_id = 0;
UPDATE education_class SET org_id = 0;
UPDATE employee_adjustments SET org_id = 0;
UPDATE employee_advances SET org_id = 0;
UPDATE employee_cases SET org_id = 0;
UPDATE employee_leave SET org_id = 0;
UPDATE employee_month SET org_id = 0;
UPDATE employee_overtime SET org_id = 0;
UPDATE employee_per_diem SET org_id = 0;
UPDATE employee_tax_types SET org_id = 0;
UPDATE employee_trainings SET org_id = 0;
UPDATE employees SET org_id = 0;
UPDATE employment SET org_id = 0;
UPDATE entity_subscriptions SET org_id = 0;
UPDATE entity_types SET org_id = 0;
UPDATE entitys SET org_id = 0;
UPDATE entry_forms SET org_id = 0;
UPDATE evaluation_points SET org_id = 0;
UPDATE fields SET org_id = 0;
UPDATE fiscal_years SET org_id = 0;
UPDATE forms SET org_id = 0;
UPDATE gls SET org_id = 0;
UPDATE intake SET org_id = 0;
UPDATE interns SET org_id = 0;
UPDATE internships SET org_id = 0;
UPDATE item_category SET org_id = 0;
UPDATE item_units SET org_id = 0;
UPDATE items SET org_id = 0;
UPDATE job_reviews SET org_id = 0;
UPDATE journals SET org_id = 0;
UPDATE kin_types SET org_id = 0;
UPDATE kins SET org_id = 0;
UPDATE lead_items SET org_id = 0;
UPDATE leads SET org_id = 0;
UPDATE leave_types SET org_id = 0;
UPDATE leave_work_days SET org_id = 0;
UPDATE loan_monthly SET org_id = 0;
UPDATE loan_types SET org_id = 0;
UPDATE loans SET org_id = 0;
UPDATE locations SET org_id = 0;
UPDATE pay_groups SET org_id = 0;
UPDATE pay_scale_years SET org_id = 0;
UPDATE pay_scales SET org_id = 0;
UPDATE payroll_ledger SET org_id = 0;
UPDATE pc_allocations SET org_id = 0;
UPDATE pc_banking SET org_id = 0;
UPDATE pc_budget SET org_id = 0;
UPDATE pc_category SET org_id = 0;
UPDATE pc_expenditure SET org_id = 0;
UPDATE pc_items SET org_id = 0;
UPDATE period_tax_rates SET org_id = 0;
UPDATE period_tax_types SET org_id = 0;
UPDATE periods SET org_id = 0;
UPDATE phases SET org_id = 0;
UPDATE project_cost SET org_id = 0;
UPDATE project_locations SET org_id = 0;
UPDATE project_staff SET org_id = 0;
UPDATE project_staff_costs SET org_id = 0;
UPDATE project_types SET org_id = 0;
UPDATE projects SET org_id = 0;
UPDATE quotations SET org_id = 0;
UPDATE review_category SET org_id = 0;
UPDATE review_points SET org_id = 0;
UPDATE shift_schedule SET org_id = 0;
UPDATE shifts SET org_id = 0;
UPDATE skill_category SET org_id = 0;
UPDATE skill_types SET org_id = 0;
UPDATE skills SET org_id = 0;
UPDATE stock_lines SET org_id = 0;
UPDATE stocks SET org_id = 0;
UPDATE stores SET org_id = 0;
UPDATE sub_fields SET org_id = 0;
UPDATE subscription_levels SET org_id = 0;
UPDATE sys_dashboard SET org_id = 0;
UPDATE sys_emailed SET org_id = 0;
UPDATE sys_emails SET org_id = 0;
UPDATE sys_files SET org_id = 0;
UPDATE sys_news SET org_id = 0;
UPDATE sys_queries SET org_id = 0;
UPDATE tasks SET org_id = 0;
UPDATE tax_rates SET org_id = 0;
UPDATE tax_types SET org_id = 0;
UPDATE tender_items SET org_id = 0;
UPDATE tender_types SET org_id = 0;
UPDATE tenders SET org_id = 0;
UPDATE timesheet SET org_id = 0;
UPDATE trainings SET org_id = 0;
UPDATE transaction_details SET org_id = 0;
UPDATE transaction_links SET org_id = 0;
UPDATE transactions SET org_id = 0;
UPDATE workflow_phases SET org_id = 0;
UPDATE workflow_sql SET org_id = 0;
UPDATE workflows SET org_id = 0;





